Us 6 blindpage
WildCodeSchool/2022-03-php-remotefr-p2-blind-test pull request #2
Opened 2022-04-16 22:39 UTC by trueChoan

Yo l'équipe ! =)

Premier jet sur la structure du choix des catégories et de la premiere page du jeu. 

J'ai repris le cours de JF pour intégré les noms des catégories dynamiquement, pensez a faire un php migration.php pour mettre a jour votre db.

2022-04-17 06:48 UTC, Desbiens-Mickael approved these changes
Ben dit donc tu ne chômes pas, bon boulot ;)

2022-04-17 10:40 UTC, TusharChowdhury97 approved these changes
Great job!

2022-04-19 08:41 UTC, callejonmelissa commented
GG BRO !

2022-04-19 10:22 UTC, jfm-wcs requested changes
ok côté test en local, à voir qq modifs de code (fonts, etc.)

2022-04-19 10:22 UTC, jfm-wcs commented on public/assets/css/style.css
> +
on peut s'en passer vue qu'il ya gg fonts. Penser à supprimer les fichiers associés.

2022-04-19 10:22 UTC, jfm-wcs commented on src/View/Game/index.html.twig
> +				<input class="button" type="submit" value="Passer">
pas possible 2 boutons submit. si besoin, possible de mettre 1 a[href]

2022-04-19 10:22 UTC, jfm-wcs commented on src/View/Quizz/index.html.twig
> +				<div class="  sm-col-12 col-lg-6">
col-sm-12 plutôt

2022-04-19 10:22 UTC, jfm-wcs commented on src/View/include/_navbar.html.twig
> +			<a href="/ " rel="Accueil">
espace après le /

2022-04-19 16:47 UTC, trueChoan commented on src/View/Game/index.html.twig
> +				<input class="button" type="submit" value="Passer">
A la place du type j'ai mis onclick="window.location.href = '...';"  c'est correct ?

2022-04-21 07:25 UTC, jfm-wcs requested changes

2022-04-21 07:25 UTC, jfm-wcs commented on src/View/Game/index.html.twig
> +			</div>
```
<a href="/game/track&id={{ track.id }}">passer</a>
````

2022-04-21 12:48 UTC, jfm-wcs reviewed
Ça me paraît bien, j'ai juste une question. Quelle est la différence entre la route /game (qui pointe vers le QuizzController) et la route /category (qui pointe vers CategoryController) ? Ne ferait-elle pas doublon ? 🤔

2022-04-21 13:16 UTC, trueChoan commented
> Ça me paraît bien, j'ai juste une question. Quelle est la différence entre la route /game (qui pointe vers le QuizzController) et la route /category (qui pointe vers CategoryController) ? Ne ferait-elle pas doublon ? 🤔. Pourquoi ne pas avoir les pages :
> 
> * /quizz (/game actuellement)
> * puis /quizz?category=rap, /quizz?category=pop, etc.
>   ?

J'avais pas changé le nom de la route pour game c'est peut etre plus explicite avec le dernier push.

La route category mène a la page de choix des category; l'user choisis une catégorie et ça renvoie a la page du quizz avec la route quizz.

2022-04-21 13:36 UTC, callejonmelissa approved these changes

2022-04-22 10:15 UTC, jfm-wcs approved these changes

2022-04-22 10:15 UTC, merged