Us 15.3
WildCodeSchool/2022-03-php-remotefr-p2-blind-test pull request #23
Opened 2022-05-06 19:00 UTC by callejonmelissa

- un lien "mon compte" dans la nav dirigeant vers la page de connexion (login)
- lorsqu'on appuie sur le bouton connexion nous sommes dirigé vers le tableau de bord (dashboard)
- page d'inscription (register)

2022-05-06 19:35 UTC, Desbiens-Mickael approved these changes

2022-05-06 19:35 UTC, TusharChowdhury97 approved these changes

2022-05-07 17:36 UTC, jfm-wcs requested changes

2022-05-07 17:36 UTC, jfm-wcs commented on database.sql
>  -- Structure de la table `user`
je pense que cela ne sert pas à grand chose d'insérer un utilisateur en BDD avec un mot de passe en clair car tu as mis la fonction password_verify() dans le controleur UserController à la méthode login() (ce qui est très bien au passage) mais ne pourra jamais marcher sur la string `motdepasse` 😉, you see ?

2022-05-07 17:36 UTC, jfm-wcs commented on public/assets/css/_index.css
> +    font-size: 18px;
préfère les unités proportionnelles `rem`  😉

2022-05-07 17:36 UTC, jfm-wcs commented on public/assets/css/_index.css
> +    font-size: 13px;
idem, préfère les unités proportionnelles `rem`  😉

2022-05-07 17:36 UTC, jfm-wcs commented on public/assets/css/_index.css
> +    font-size: 13px;
idem, préfère les unités proportionnelles `rem`  😉

2022-05-07 17:36 UTC, jfm-wcs commented on src/View/Login/register.html.twig
> +                </div>
sans balise `<form>` ça ne va pas marcher je pense 🤔

2022-05-07 17:36 UTC, jfm-wcs commented on src/routes.php
> +    'register' => ['RegisterController', 'index',],
Pourquoi ne pas faire une méthode `register()` dans le `UserController` ? cela t'éviterait de créer un nouveau controller, non ?

2022-05-07 17:39 UTC, jfm-wcs commented
Évidemment il y a maintenant quelques conflits puisque la us_15 vient d'être validée. Du coup j'en ai profité pour noter quelques remarques sur le css (qui se retrouvait étrangement sur cette branche 🙃).
__Autre info importante__, il manque la méthode register() pour la partie de création de compte... 
Mais ça prend forme 👍. tu n'es plus très loin de la victoire 💃 🙂

2022-05-07 17:42 UTC, jfm-wcs commented on src/routes.php
> +    'register' => ['RegisterController', 'index',],
et d'ailleurs, la méthode `login()` existe dans le `UseController`, alors pas besoin de créer un `LoginController` 🧙

2022-05-08 09:58 UTC, callejonmelissa commented
@jfm-wcs Merci JF d’avoir pris de ton temps ce week-end pour commenter ma PR, je vais me poser et améliorer tout ça

2022-05-09 07:58 UTC, trueChoan approved these changes

2022-05-11 10:11 UTC, closed without merging