Us 7
WildCodeSchool/2022-03-php-remotefr-p2-blind-test pull request #4
Opened 2022-04-18 22:16 UTC by Desbiens-Mickael

2022-04-19 16:59 UTC, trueChoan approved these changes
normalement le footer est réglé sur ma branche faudra faire gaffe au moment de merge

2022-04-19 16:59 UTC, trueChoan commented on public/assets/css/style.css
> +    --bs-gradient:url(https://cdn.discordapp.com/attachments/963093723124748368/964186826283839549/noise.png ),radial-gradient(ellipse at center,#5f9ece 0,#5f9ece 24%,#724589 100%);
ya encore cette vieille url pour le noise.png xD

2022-04-19 16:59 UTC, trueChoan commented on src/View/include/_footer.html.twig
> +        <footer>
il faut une class mt-auto dans le footer pour qu'il reste en bas. ou dans le css

2022-04-20 16:42 UTC, TusharChowdhury97 approved these changes

2022-04-21 13:03 UTC, jfm-wcs requested changes
quelques petites modifs et on est bon 👍

2022-04-21 13:03 UTC, jfm-wcs commented on src/View/About_us/about_us.html.twig
> +            <img src="../../../assets/images/photo-rock.jpeg" alt="..." class="us-img img-fluid shadow mt-sm-2">
ça fonctionne avec cette adresse `../../../assets/images/photo-rock.jpeg` ? 🤔
J'aurais plutôt vu `/assets/images/photo-rock.jpeg` puisqu'on ouvre le server en racine du dossier public.

2022-04-21 13:03 UTC, jfm-wcs commented on src/View/include/_footer.html.twig
> +        <footer>
oui mais ça implique d'avoir mis `d-flex flex-column h-100` sur le `body` (et non sur main) et `h-100` sur `<html>` aussi 😉

2022-04-21 13:27 UTC, trueChoan commented on src/View/include/_footer.html.twig
> +        <footer>
AH merci JF c'est pour ça que chez moi ça marchait pas avec just eun h-100 sur le body, j'ai du mettre 100vh dans le css pour coller le footer en bas.

2022-04-21 13:36 UTC, callejonmelissa approved these changes

2022-04-22 10:24 UTC, jfm-wcs approved these changes

2022-04-22 10:24 UTC, merged